import type { FastifyInstance } from 'fastify'
import { createReadStream } from 'node:fs'
import { stat } from 'node:fs/promises'
import { join } from 'node:path'
import { createHmac } from 'node:crypto'

/**
 * Validates an NFS/local storage signed token and streams the file.
 *
 * Token format: base64url(key).expiresAt.hmacSignature
 * This matches the format generated by NfsAdapter.signedUrl()
 */
export async function storageServeRoutes(fastify: FastifyInstance): Promise<void> {
  fastify.get('/storage/serve/:token', async (request, reply) => {
    const { token } = request.params as { token: string }
    const tokenSecret = process.env['STORAGE_ENCRYPTION_KEY'] ?? ''

    // Parse token: encodedKey.expiresAt.signature
    const parts = token.split('.')
    if (parts.length !== 3) {
      return reply.status(400).send({ error: 'Invalid token format' })
    }

    const [encodedKey, expiresAtStr, providedSignature] = parts as [string, string, string]

    // Verify expiry
    const expiresAt = parseInt(expiresAtStr, 10)
    const now = Math.floor(Date.now() / 1000)
    if (isNaN(expiresAt) || now > expiresAt) {
      return reply.status(410).send({ error: 'Token has expired' })
    }

    // Decode key
    let key: string
    try {
      key = Buffer.from(encodedKey, 'base64url').toString('utf8')
    } catch {
      return reply.status(400).send({ error: 'Invalid token encoding' })
    }

    // Verify HMAC signature
    const payload = `${key}:${expiresAt}`
    const expectedSignature = createHmac('sha256', tokenSecret).update(payload).digest('hex')

    if (expectedSignature !== providedSignature) {
      return reply.status(403).send({ error: 'Invalid token signature' })
    }

    // Resolve file path from the storage root
    const storagePath = process.env['LOCAL_STORAGE_PATH'] ?? join(process.cwd(), 'data', 'backups')
    const filePath = join(storagePath, key.replace(/\.\./g, '').replace(/^\/+/, ''))

    try {
      const fileStat = await stat(filePath)
      if (!fileStat.isFile()) {
        return reply.status(404).send({ error: 'File not found' })
      }

      void reply.header('Content-Length', fileStat.size)
      void reply.header('Content-Disposition', `attachment; filename="${filePath.split('/').pop()}"`)

      return reply.send(createReadStream(filePath))
    } catch {
      return reply.status(404).send({ error: 'File not found' })
    }
  })
}
